version: "2"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./server/nginx:/etc/nginx/conf.d
      - web_cache:/var/cache/nginx
    networks:
      network:
        ipv4_address: 172.130.0.2
    ports:
      - 80:80
      - 443:443
    restart: always
  node_et:
    depends_on:
      - nginx
    image: node:8
    volumes:
      - web_cache:/var/cache/nginx
    networks:
      network:
        ipv4_address: 172.130.0.4
    environment:
      WORDPRESS_HOST: https://www.extremetech.com
      NGINX_HOST: http://nginx
      NGINX_CACHE: /var/cache/nginx/data_et
    command: [ node, /opt/example/server/index.js ]
    restart: always
volumes:
  web_cache:
networks:
  network:
    driver: bridge
    ipam:
     config:
       - subnet: 172.130.0.0/16
         gateway: 172.130.0.1
